// Code generated by internal/prompts/gen; DO NOT EDIT. Regenerate via `make prompts`.

package prompts

// ExecuteGoCodeDescription is the tool description for execute_go_code.
// Generated from internal/curated.Packages so a curated-set change
// updates both this string and internal/prompts/system.md in one shot.
const ExecuteGoCodeDescription = `Build and run Go code in a sandboxed Kubernetes pod (gVisor-isolated on GKE, runsc-free on local kind). The pod has the Go toolchain plus a prewarmed cache of curated Google Cloud + Kubernetes client packages:

  cloud.google.com/go/storage
  cloud.google.com/go/compute/apiv1
  cloud.google.com/go/container/apiv1
  cloud.google.com/go/bigquery
  cloud.google.com/go/secretmanager/apiv1
  google.golang.org/api/option
  k8s.io/apimachinery/pkg/apis/meta/v1
  k8s.io/client-go/kubernetes
  k8s.io/client-go/tools/clientcmd
  k8s.io/client-go/dynamic
  k8s.io/client-go/tools/watch

The snippet's go.mod is inherited from the prewarm lockfile so builds cache-hit at steady state (~5 s). Anything not covered above is resolved on demand via go mod tidy (slower; may re-tidy shared transitives and cache-miss).

Two input modes. Provide EXACTLY ONE:

1) SINGLE-FILE via 'code': a Go source blob. Either a snippet declaring 'func run(ctx context.Context) (any, error)' in any package other than 'main' (the wrapper provides func main(); your return value becomes result.value), OR a complete 'package main' program (you own stdout/stderr; write /app/.kode-gopher/result.json for structured output).

2) MULTI-FILE via 'files': map of path -> source. Root files (no '/' in key) share the entry-point package; subdirectory files are separate helper packages. The synthesized module name is 'kode_gopher_user' — a helper at 'helper/util.go' is imported as 'kode_gopher_user/helper'. If you include a 'go.mod' file the executor uses YOUR version pins instead of the prewarm lockfile; you take on any resulting recompile cost.

The host forwards ambient Google Cloud credentials (gcloud Application Default Credentials, plus GOOGLE_CLOUD_PROJECT if set) into the sandbox, so cloud.google.com/go/* calls work without additional setup. ADC lands at /app/.kode-gopher/creds/adc.json and GOOGLE_APPLICATION_CREDENTIALS is set for the run phase.`
