// Code generated by internal/prompts/gen; DO NOT EDIT. Regenerate via `make prompts`.

package prompts

// ExecuteGoCodeDescription is the tool description for execute_go_code.
// Generated from internal/curated.Packages so a curated-set change
// updates both this string and internal/prompts/system.md in one shot.
const ExecuteGoCodeDescription = `Build and run Go code in a sandboxed Kubernetes pod (gVisor-isolated on GKE, runsc-free on local kind). The pod has the Go toolchain plus a prewarmed cache of curated Google Cloud + Kubernetes client packages:

  cloud.google.com/go/storage
  cloud.google.com/go/compute/apiv1
  cloud.google.com/go/container/apiv1
  cloud.google.com/go/bigquery
  cloud.google.com/go/secretmanager/apiv1
  cloud.google.com/go/logging/logadmin
  cloud.google.com/go/monitoring/apiv3/v2
  cloud.google.com/go/trace/apiv1
  google.golang.org/api/option
  k8s.io/apimachinery/pkg/apis/meta/v1
  k8s.io/client-go/kubernetes
  k8s.io/client-go/tools/clientcmd
  k8s.io/client-go/dynamic
  k8s.io/client-go/tools/watch

The snippet's go.mod is inherited from the prewarm lockfile so builds cache-hit at steady state (~5 s). Anything not covered above is resolved on demand via go mod tidy (slower; may re-tidy shared transitives and cache-miss).

Two input modes. Provide EXACTLY ONE:

1) SINGLE-FILE via 'code': a Go source blob. Either a snippet declaring 'func run(ctx context.Context) (any, error)' in any package other than 'main' (the wrapper provides func main(); your return value becomes result.value), OR a complete 'package main' program (you own stdout/stderr; write /app/.kode-gopher/result.json for structured output).

2) MULTI-FILE via 'files': map of path -> source. Root files (no '/' in key) share the entry-point package; subdirectory files are separate helper packages. The synthesized module name is 'kode_gopher_user' — a helper at 'helper/util.go' is imported as 'kode_gopher_user/helper'. If you include a 'go.mod' file the executor uses YOUR version pins instead of the prewarm lockfile; you take on any resulting recompile cost.

Google Cloud calls authenticate automatically with Application Default Credentials, so cloud.google.com/go/* clients need no credential options. The identity depends on the deployment (the local developer, the signed-in user, the server's Workload Identity, or a service account); call gcp_auth_status to see it and its project. GOOGLE_CLOUD_PROJECT may be set; if it's empty, use gcp_auth_status's project_id.`
