/*
Copyright 2026 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package mcp

import (
	"context"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"sort"
	"strings"
	"testing"

	sdk "github.com/modelcontextprotocol/go-sdk/mcp"
)

var updateToolDoc = flag.Bool("update", false, "rewrite the docs site's MCP tools reference page")

const toolDocPath = "../../docs/site/src/content/docs/reference/tools.md"

// TestToolReference keeps the docs site's tools page in step with
// what the server advertises: it lists the tools over an in-memory
// MCP connection and renders their descriptions and schemas.
//
//	go test ./internal/mcp -run TestToolReference -update
func TestToolReference(t *testing.T) {
	ctx := context.Background()
	st, ct := sdk.NewInMemoryTransports()
	ss, err := New(Config{}).newSDKServer().Connect(ctx, st, nil)
	if err != nil {
		t.Fatal(err)
	}
	defer func() { _ = ss.Close() }()
	cs, err := sdk.NewClient(&sdk.Implementation{Name: "tooldoc", Version: "0"}, nil).Connect(ctx, ct, nil)
	if err != nil {
		t.Fatal(err)
	}
	defer func() { _ = cs.Close() }()
	res, err := cs.ListTools(ctx, nil)
	if err != nil {
		t.Fatal(err)
	}
	tools := res.Tools
	sort.Slice(tools, func(i, j int) bool { return tools[i].Name < tools[j].Name })

	var b strings.Builder
	b.WriteString(`---
title: MCP tools
description: The tools kode-gopher's MCP server offers, with their descriptions and input and output schemas.
---

<!-- Code generated by TestToolReference in internal/mcp; DO NOT EDIT. Regenerate: go test ./internal/mcp -run TestToolReference -update -->

This page is generated from what the server advertises: the descriptions and schemas here are exactly what an MCP client, and so the model, receives. A test regenerates it and fails CI if it drifts.
`)
	for _, tool := range tools {
		fmt.Fprintf(&b, "\n## `%s`\n\n", tool.Name)
		if tool.Title != "" {
			b.WriteString(tool.Title + "\n\n")
		}
		b.WriteString("**Description**\n\n")
		b.WriteString("```text\n" + strings.TrimSpace(tool.Description) + "\n```\n\n")
		b.WriteString("**Input**\n\n")
		b.WriteString(schemaTable(t, tool.InputSchema))
		if tool.OutputSchema != nil {
			b.WriteString("\n**Output** (structured content)\n\n")
			b.WriteString(schemaTable(t, tool.OutputSchema))
		}
	}
	got := b.String()

	if *updateToolDoc {
		if err := os.WriteFile(toolDocPath, []byte(got), 0o644); err != nil {
			t.Fatal(err)
		}
		return
	}
	want, err := os.ReadFile(toolDocPath)
	if err != nil {
		t.Fatalf("%v (run: go test ./internal/mcp -run TestToolReference -update)", err)
	}
	if string(want) != got {
		t.Errorf("%s is out of date with the server's tools; run: go test ./internal/mcp -run TestToolReference -update", toolDocPath)
	}
}

type jsonSchema struct {
	Type        any                    `json:"type"`
	Description string                 `json:"description"`
	Properties  map[string]*jsonSchema `json:"properties"`
	Required    []string               `json:"required"`
	Items       *jsonSchema            `json:"items"`
}

// UnmarshalJSON accepts the boolean schema `true` (any value), which
// the SDK emits for fields typed `any`.
func (s *jsonSchema) UnmarshalJSON(data []byte) error {
	if string(data) == "true" || string(data) == "false" {
		*s = jsonSchema{}
		return nil
	}
	type plain jsonSchema
	return json.Unmarshal(data, (*plain)(s))
}

// schemaTable renders an object schema's properties, one level of
// nested object properties included, as a Markdown table.
func schemaTable(t *testing.T, schema any) string {
	t.Helper()
	raw, err := json.Marshal(schema)
	if err != nil {
		t.Fatal(err)
	}
	var s jsonSchema
	if err := json.Unmarshal(raw, &s); err != nil {
		t.Fatal(err)
	}
	if len(s.Properties) == 0 {
		return "None.\n"
	}
	var b strings.Builder
	b.WriteString("| Field | Type | Description |\n|---|---|---|\n")
	var rows func(prefix string, s *jsonSchema)
	rows = func(prefix string, s *jsonSchema) {
		required := map[string]bool{}
		for _, r := range s.Required {
			required[r] = true
		}
		names := make([]string, 0, len(s.Properties))
		for n := range s.Properties {
			names = append(names, n)
		}
		sort.Strings(names)
		for _, n := range names {
			p := s.Properties[n]
			field := "`" + prefix + n + "`"
			if required[n] {
				field += " (required)"
			}
			fmt.Fprintf(&b, "| %s | %s | %s |\n", field, typeName(p), cell(p.Description))
			if prefix == "" && len(p.Properties) > 0 {
				rows(n+".", p)
			}
		}
	}
	rows("", &s)
	return b.String()
}

func typeName(s *jsonSchema) string {
	var name string
	switch v := s.Type.(type) {
	case string:
		name = v
	case []any:
		var parts []string
		for _, p := range v {
			if p != "null" {
				parts = append(parts, fmt.Sprint(p))
			}
		}
		name = strings.Join(parts, " or ")
	default:
		name = "any"
	}
	if name == "array" && s.Items != nil {
		return "array of " + typeName(s.Items)
	}
	return name
}

// cell makes a description safe for a Markdown table cell.
func cell(s string) string {
	s = strings.ReplaceAll(s, "|", `\|`)
	return strings.Join(strings.Fields(s), " ")
}
