/*
Copyright 2026 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package main

import (
	"bytes"
	"flag"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

var updateCLIDoc = flag.Bool("update", false, "rewrite the docs site's CLI reference page from the binary's help")

const cliDocPath = "../../docs/site/src/content/docs/reference/cli.md"

// TestCLIReference keeps the docs site's CLI reference page in step
// with the binary: the page is the real `-h` output of each
// subcommand. The flags use flag.ExitOnError, so help can't be
// captured in-process; build the binary and run it instead.
//
//	go test ./cmd/kode-gopher -run TestCLIReference -update
func TestCLIReference(t *testing.T) {
	if testing.Short() {
		t.Skip("builds the binary")
	}
	if _, err := exec.LookPath("go"); err != nil {
		t.Skip("no go on PATH")
	}
	bin := filepath.Join(t.TempDir(), "kode-gopher")
	if out, err := exec.Command("go", "build", "-o", bin, ".").CombinedOutput(); err != nil {
		t.Fatalf("go build: %v\n%s", err, out)
	}
	help := func(args ...string) string {
		var stderr bytes.Buffer
		cmd := exec.Command(bin, args...)
		cmd.Stdout, cmd.Stderr = &stderr, &stderr
		if err := cmd.Run(); err != nil {
			t.Fatalf("kode-gopher %s: %v\n%s", strings.Join(args, " "), err, stderr.String())
		}
		return strings.TrimRight(stderr.String(), "\n")
	}

	var b strings.Builder
	b.WriteString(`---
title: CLI
description: Every kode-gopher subcommand and flag, as printed by the binary's own help.
---

<!-- Code generated by TestCLIReference in cmd/kode-gopher; DO NOT EDIT. Regenerate: go test ./cmd/kode-gopher -run TestCLIReference -update -->

This page is the help output of the ` + "`kode-gopher`" + ` binary built from the current sources. A test regenerates it and fails CI if it drifts.

Flags take one dash or two (` + "`-namespace`" + ` and ` + "`--namespace`" + ` are the same).
`)
	for _, sec := range []struct {
		title, intro string
		args         []string
	}{
		{"kode-gopher", "", []string{"--help"}},
		{"kode-gopher exec", "Runs one Go file in a sandbox and prints the outcome. Useful for checking a cluster setup without an MCP client; see [Getting started](/getting-started/sandbox-cluster/#check-it-from-the-command-line).", []string{"exec", "-h"}},
		{"kode-gopher serve", "The MCP server. Over stdio for local use ([Getting started](/getting-started/connect/)), or streamable HTTP for a shared deployment ([Deploy for a team](/deploy/)).", []string{"serve", "-h"}},
		{"kode-gopher auth", "", []string{"auth", "-h"}},
	} {
		b.WriteString("\n## `" + sec.title + "`\n\n")
		if sec.intro != "" {
			b.WriteString(sec.intro + "\n\n")
		}
		b.WriteString("```text\n" + help(sec.args...) + "\n```\n")
	}
	got := b.String()

	if *updateCLIDoc {
		if err := os.WriteFile(cliDocPath, []byte(got), 0o644); err != nil {
			t.Fatal(err)
		}
		return
	}
	want, err := os.ReadFile(cliDocPath)
	if err != nil {
		t.Fatalf("%v (run: go test ./cmd/kode-gopher -run TestCLIReference -update)", err)
	}
	if string(want) != got {
		t.Errorf("%s is out of date with the binary's help; run: go test ./cmd/kode-gopher -run TestCLIReference -update", cliDocPath)
	}
}
